version: '3.8'
services:
  web:
    build: 
      context: ..
      dockerfile: infrastructure/Dockerfile.dev
      target: dev
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - ..:/app
      - /app/node_modules
      - /app/.next
    command: npm run dev
    restart: unless-stopped
    develop:
      watch:
        # Sync source files for hot reload
        - action: sync
          path: ./src
          target: /app/src
          ignore:
            - node_modules/
            - .next/
        # Sync configuration files
        - action: sync
          path: ./package.json
          target: /app/package.json
        - action: sync
          path: ./tsconfig.json
          target: /app/tsconfig.json
        - action: sync
          path: ./next.config.ts
          target: /app/next.config.ts
        - action: sync
          path: ./postcss.config.mjs
          target: /app/postcss.config.mjs
        - action: sync
          path: ./eslint.config.mjs
          target: /app/eslint.config.mjs
        # Rebuild when dependencies change
        - action: rebuild
          path: package.json
        - action: rebuild
          path: package-lock.json 